apiVersion: apps/v1
kind: Deployment
metadata:
 name: javahelmspring
spec:
 replicas: {{ .Values.replicaCount }}
 selector:
  matchLabels:
   app: javahelmspring
 template:
  metadata:
   labels:
    app: javahelmspring
  spec:
   containers:
   - name: javahelmspring
     image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
     ports:
     - containerPort: 8080