name: Deploy Spring Boot to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Build Jar
      run: |
          cd app 
          mvn clean package -DskipTests

    - name: Docker Build
      run: |
          cd app
          docker build --no-cache -t springboot-app .

    - name: Login ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 198413840424.dkr.ecr.ap-south-1.amazonaws.com

    - name: Push Image
      run: |
        cd app
        IMAGE_TAG=${GITHUB_SHA}
        docker tag springboot-app:latest 198413840424.dkr.ecr.ap-south-1.amazonaws.com/springboot-app:$IMAGE_TAG
        docker push 198413840424.dkr.ecr.ap-south-1.amazonaws.com/springboot-app:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Configure kubectl
      run: |
          aws eks update-kubeconfig --region ap-south-1 --name java-cluster
          kubectl get nodes 

    - name: Helm Deploy
      run: helm upgrade springboot-app helm/springboot --set image.tag=${IMAGE_TAG} \
           --atomic \
           --timeout 3m

    
    - name: Debug Image Tag
      run: echo "IMAGE_TAG is $IMAGE_TAG"